// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"red-auth/app/auth/delivery/http"
	"red-auth/app/auth/repository/oauth2"
	"red-auth/app/auth/usecase"
)

// Injectors from wire.go:

func InitAuthController() http.AuthController {
	authRepository := oauth2.NewOAuth2AuthRepository()
	authUseCase := usecase.NewAuthUseCase(authRepository)
	authController := http.NewAuthController(authUseCase)
	return authController
}
